run:
  timeout: 5m
  tests: false
  skip-files:
    - .*(_mock.go)$

output:
  sort-results: true

linters-settings:
  dupl:
    # tokens count to trigger issue, 150 by default
    threshold: 100
  errcheck:
    check-type-assertions: true
  gocritic:
    enabled-tags:
      - performance
      - style
      - diagnostic
    disabled-tags:
      - experimental
    settings: # settings passed to gocritic
      hugeParam:
        sizeThreshold: 256 # Receivers still must be <80 bytes
  cyclop:
    # The maximal code complexity to report.
    max-complexity: 30
  godot:
    capital: true
    exclude:
      - '^(\s)*(@).*$'
  godox:
    keywords: # default keywords are TODO, BUG, and FIXME, these can be overwritten by this setting
      - FIXME
      - HACK # marks hack-arounds that should be removed before merging
  goimports:
    # put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    local-prefixes: gitlab.test.igdcs.com/,gitlab.global.ingenico.com
  gomodguard:
    blocked:
      modules:
        - gitlab.test.igdcs.com/finops/nextgen/utils/basics/igconfig.git/v2:
            recommendations:
              - github.com/worldline-go/igconfig
        - gitlab.test.igdcs.com/finops/nextgen/utils/basics/igconfig.git:
            recommendations:
              - github.com/worldline-go/igconfig
        - gitlab.test.igdcs.com/finops/nextgen/utils/basics/reformat.git:
            recommendations:
              - github.com/worldline-go/reformat
        - gitlab.test.igdcs.com/finops/nextgen/utils/basics/keycloak.git:
            recommendations:
              - gitlab.test.igdcs.com/finops/nextgen/utils/basics/keycloak.git/v2
        - gitlab.test.igdcs.com/finops/nextgen/utils/basics/iglog.git:
            recommendations:
              - github.com/rs/zerolog
        - gitlab.test.igdcs.com/finops/nextgen/utils/basics/igbatchlog.git:
            recommendations:
              - github.com/rs/zerolog
        - gitlab.test.igdcs.com/finops/nextgen/utils/db/igmigrator.git:
            recommendations:
              - github.com/worldline-go/igmigrator
  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment
  lll:
    line-length: 140
  misspell:
    locale: US
  nolintlint:
    require-explanation: true
    require-specific: true
  gosmopolitan:
    allow-time-local: true

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - maligned
    - funlen
    - exhaustivestruct
    - exhaustruct
    - tagliatelle
    - scopelint
    - ifshort
    - structcheck
    - interfacer
    - nosnakecase
    - varcheck
    - golint
    - deadcode
    - wsl
    - rowserrcheck
    - sqlclosecheck
    - wastedassign
    - gomoddirectives
    - depguard
    - varnamelen
    - gci

issues:
  exclude:
    - "could not import C"

  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - linters:
        - goerr113
      text: "do not define dynamic errors"
    - linters:
        - lll
      source: "`"

  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 5

severity:
  default-severity: error
